CREATE SCHEMA IF NOT EXISTS igor;

CREATE TABLE igor.job (
    id INTEGER PRIMARY KEY auto_increment,
    version INTEGER,
    name VARCHAR(256) NOT NULL UNIQUE,
    content TEXT
);
CREATE SEQUENCE JOB_ID_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE TABLE igor.service (
    id INTEGER PRIMARY KEY auto_increment,
    version INTEGER,
    name VARCHAR(256) NOT NULL UNIQUE,
    content TEXT
);
CREATE SEQUENCE SERVICE_ID_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE TABLE igor.job_execution (
    id INTEGER PRIMARY KEY auto_increment,
    version INTEGER,
    job_id INTEGER NOT NULL,
    content TEXT
);
CREATE SEQUENCE JOB_EXECUTION_ID_SEQUENCE START WITH 1 INCREMENT BY 1;

